window.GENRES.push(
{n:15,id:'story',name:'Interactive Story',sub:'Dialogue, romance, choice',cat:'ad',action:'Выбирает реплику или развитие сцены',signal:'Вертикальный fit',desc:'Сильный формат для narrative, romance, fashion и life-sim. Ценность создают конфликт, персонаж и немедленное последствие выбора.',loop:'конфликт → 2–3 выбора → реакция → cliffhanger',variants:'диалоги, отношения, секреты, одежда',engine:'choice',related:['makeover','rescue','hidden']},
{n:16,id:'bubble',name:'Bubble Shooter',sub:'Aim, color match, rescue',cat:'extra core',action:'Прицеливается и стреляет цветным шаром',signal:'Стабильный',desc:'Зрелая механика с понятным управлением и приятными цепными падениями. Часто усиливается спасением объекта внизу поля.',loop:'прицел → выстрел → match → падение',variants:'цвета, препятствия, rescue, ограниченные шары',engine:'grid',related:['blast','match3','rescue']},
{n:17,id:'cooking',name:'Cooking / Orders',sub:'Serve, prepare, restaurant',cat:'extra ad',action:'Готовит блюдо и выполняет заказ',signal:'Сильная оболочка',desc:'Может быть самостоятельной мини-игрой или темой для Merge, Sort и Match‑3. Хорошо показывает цель и награду за действие.',loop:'подготовить → собрать → отдать заказ',variants:'нарезка, жарка, сборка, очередь клиентов',engine:'progress',related:['merge','sort','match3']},
{n:18,id:'makeover',name:'Makeover / Dress-up',sub:'Decoration, repair, before/after',cat:'extra ad',action:'Выбирает одежду, декор или вариант ремонта',signal:'Эмоциональный fit',desc:'Сцена «до/после» создаёт мгновенный визуальный payoff. Намеренно плохие варианты усиливают интерактивный выбор.',loop:'проблема → выбор предмета → transformation',variants:'одежда, волосы, интерьер, ремонт',engine:'choice',related:['story','merge','rescue']},
{n:19,id:'idle',name:'Idle / Tycoon 2D',sub:'Resources, workers, build',cat:'extra',action:'Собирает ресурс и открывает производство',signal:'Гибридный fit',desc:'Позволяет casualизировать рекламу симулятора или стратегии. Требует больше систем, но даёт заметный прогресс за короткую сессию.',loop:'собрать → перенести → построить → ускорить',variants:'база, магазин, ферма, фабрика, рабочие',engine:'progress',related:['merge','cooking','parking']},
{n:20,id:'jigsaw',name:'Jigsaw / Art Puzzle',sub:'Snap pieces, reveal',cat:'extra',action:'Перетаскивает детали и собирает изображение',signal:'Низкая сложность',desc:'Спокойный и дешёвый шаблон с понятным drag-and-snap. Финальная иллюстрация работает как награда и reveal.',loop:'drag детали → snap → открыть изображение',variants:'комнаты, персонажи, животные, картины',engine:'scene',related:['hidden','coloring','story']},
{n:21,id:'coloring',name:'Coloring / Scratch',sub:'Paint-by-number, reveal',cat:'extra',action:'Закрашивает области или стирает слой',signal:'Дешёвый рескин',desc:'Простая реализация и широкая тематическая вариативность. Swipe-эффекты хорошо сочетаются с визуальным ASMR.',loop:'tap или swipe → заполнение → reveal',variants:'раскраска, номера, scratch, узоры',engine:'scene',related:['jigsaw','hidden','draw']}
);
