window.GENRES=[
{n:1,id:'match3',name:'Match‑3',sub:'Swap, goals, obstacles, orders',cat:'core',action:'Меняет элементы, собирает линии и выполняет цель',signal:'Масштаб',desc:'Базовый обязательный шаблон. Конкурентные версии связывают перестановку фишек с заказом, ремонтом, спасением или очисткой препятствий.',loop:'3–8 свопов → комбо → визуальное последствие',variants:'товары, кухня, ремонт, персонажи, бустеры',engine:'grid',related:['blast','tile','cooking']},
{n:2,id:'merge',name:'Merge',sub:'Grid, Drop, Serve, Repair',cat:'core growth',action:'Объединяет одинаковые объекты и открывает следующий tier',signal:'Масштаб + рост',desc:'Один из главных источников роста puzzle. Хорошо масштабируется от чистого поля до сюжетных сцен «создай, обслужи, почини».',loop:'merge → новый объект → заказ или улучшение',variants:'еда, косметика, оружие, животные, ресурсы',engine:'grid',related:['cooking','idle','makeover']},
{n:3,id:'sort',name:'Sort',sub:'Water, Ball, Goods, Cake, Hexa',cat:'core growth',action:'Распределяет цвета и предметы по контейнерам',signal:'Быстрый рост',desc:'Сильный современный формат с мгновенно понятным движением от хаоса к порядку. Легко менять оболочку без изменения логики.',loop:'выбрать стопку → переместить → очистить контейнер',variants:'жидкости, товары, торты, блоки, пассажиры',engine:'slots',related:['screw','parking','cooking']},
{n:4,id:'tile',name:'Tile / Triple Match',sub:'Tray, layers, Mahjong',cat:'core',action:'Выбирает плитки и собирает пары или тройки',signal:'Стабильный спрос',desc:'Зрелый массовый формат. Для лёгкой 2D-сборки достаточно слоёв плиток и нижнего tray без тяжёлой 3D-кучи.',loop:'выбор плитки → слот tray → тройка исчезает',variants:'фрукты, предметы, mahjong, тематические наборы',engine:'slots',related:['match3','solitaire','hidden']},
{n:5,id:'blast',name:'Blast',sub:'Tap-to-clear, boosters, chains',cat:'core',action:'Нажимает на группы и запускает цепные реакции',signal:'Масштаб',desc:'Крупный зрелый формат. Рекламный loop становится сильнее, когда очистка поля спасает героя, ломает препятствие или выполняет заказ.',loop:'tap по группе → blast → бонус → прогресс цели',variants:'кубы, игрушки, блоки, препятствия, rescue',engine:'grid',related:['match3','rescue','block']},
{n:6,id:'block',name:'Block Puzzle',sub:'Blockdoku, Block Jam, lines',cat:'core growth',action:'Размещает фигуры и освобождает поле',signal:'Рост',desc:'Hybrid-puzzle с простым drag-and-drop и широким диапазоном сложности: от заполнения линий до направленного Block Jam.',loop:'перетащить фигуру → заполнить линию → очистить',variants:'сетка, области, jam, цветовые цели',engine:'grid',related:['arrow','parking','blast']},
{n:7,id:'screw',name:'Screw / Nuts & Bolts',sub:'Order, slots, plates',cat:'growth',action:'Выкручивает винты в правильном порядке',signal:'Быстрый рост',desc:'Популярную «3D» идею можно реализовать плоскими спрайтами. Ценность создаёт порядок действий, а не настоящая физика.',loop:'выбрать винт → занять слот → освободить пластину',variants:'цвета, замки, слои, ограниченные слоты',engine:'slots',related:['sort','arrow','draw']}
];
