window.GENRES.push(
{n:8,id:'rescue',name:'Rescue / Tricky Puzzle',sub:'Pin Pull, choose tool, fix scene',cat:'ad',action:'Спасает персонажа и выбирает решение',signal:'Ad-native',desc:'Один из сильнейших рекламных шаблонов: проблема читается мгновенно, ошибочный выбор даёт драматическое последствие, затем управление получает пользователь.',loop:'опасность → выбор → последствие → rescue',variants:'штифты, инструменты, комнаты, погода, ловушки',engine:'scene',related:['draw','story','blast']},
{n:9,id:'arrow',name:'Arrow / Tap Away',sub:'Out, direction, free exit',cat:'growth ad',action:'Убирает объекты только по свободному направлению',signal:'Breakout',desc:'Поле выглядит сложным, но правило считывается без обучения. Уровни дёшево масштабируются изменением направлений и блокировок.',loop:'найти свободную стрелку → tap → открыть путь',variants:'стрелки, блоки, змеи, направленные элементы',engine:'path',related:['parking','block','screw']},
{n:10,id:'parking',name:'Parking / Traffic',sub:'Jam, buses, unblock',cat:'growth ad',action:'Выводит машины или пассажиров в нужном порядке',signal:'Рост + ad fit',desc:'Сочетает знакомую ситуацию с логикой порядка. Ошибочное действие немедленно создаёт пробку или блокировку.',loop:'выбрать объект → проверить путь → освободить слот',variants:'машины, автобусы, пассажиры, склад, зал',engine:'path',related:['arrow','sort','block']},
{n:11,id:'hidden',name:'Hidden Object',sub:'Spot the Difference, seek',cat:'ad',action:'Ищет объекты, ошибки или различия',signal:'Универсальный',desc:'Пользователь начинает решать ещё до первого нажатия. Особенно удобен для массовой генерации уровней и тематических рескинов.',loop:'сканировать сцену → tap → подсветить прогресс',variants:'объекты, различия, ошибки, silhouettes',engine:'scene',related:['jigsaw','story','tile']},
{n:12,id:'word',name:'Word Puzzle',sub:'Connect, fill, categories',cat:'growth',action:'Соединяет буквы и группирует слова',signal:'Новый рост',desc:'Устойчивый формат с обновлением через word categorization, word solitaire и гибриды поиска общего признака.',loop:'выбрать буквы или слова → проверить → заполнить',variants:'connect, пропуски, категории, фразы',engine:'slots',related:['solitaire','tile','hidden']},
{n:13,id:'draw',name:'Draw / Erase / Cut',sub:'Connect, tangle, scene tools',cat:'ad',action:'Рисует, стирает, режет или соединяет',signal:'Ad-native',desc:'Единый scene-interaction framework создаёт множество внешне разных сценариев и подходит почти любому casual-продукту.',loop:'жест по сцене → проверка траектории → результат',variants:'мост, верёвка, стирание, пары, распутывание',engine:'scene',related:['rescue','hidden','screw']},
{n:14,id:'solitaire',name:'Solitaire / Card Sort',sub:'Cards, Mahjong Solitaire',cat:'core',action:'Перемещает карты или плитки по знакомым правилам',signal:'Зрелый рынок',desc:'Снижает стоимость обучения благодаря известным правилам. Playable лучше начинать с подготовленной середины партии и быстрых открытий.',loop:'переместить карту → открыть скрытую → собрать цепочку',variants:'классика, tri-peaks, card sort, mahjong',engine:'slots',related:['tile','word','sort']}
);
